version: '2'
services:
  db:
    image: mariadb:latest
    ports:
     - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'hilbert'
      MYSQL_DATABASE: 'hilbertspace'
      MYSQL_USER: 'hilbert'
      MYSQL_PASSWORD: 'hilbert'
    networks:
      hilbertnet:
        aliases:
          - database

  mongodb:
      image: mongo:latest
      ports:
        - '27017:27017'
      networks:
        hilbertnet:
          aliases:
            - mongodb
          
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      hilbertnet:
        aliases:
          - redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: 'database'
    networks:
      hilbertnet:
        aliases:
          - phpmyadmin

networks:
  hilbertnet:
    driver: bridge