version: '2'
services:
  db:
    image: mariadb:latest
    ports:
     - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'hilbert'
      MYSQL_DATABASE: 'hilbertspace'
      MYSQL_USER: 'hilbert'
      MYSQL_PASSWORD: 'hilbert'
    networks:
      hilbertnet:
        aliases:
          - database
          
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      hilbertnet:
        aliases:
          - redis
networks:
  hilbertnet:
    driver: bridge