---
  mongodb: 
    hosts: 
      - "127.0.0.1:27018"
      - "127.0.0.1:27017"
    user: "hilbert"
    pass: "hilbert"
    name: "hilbertspace"
    replica_set: "rs0"
  port: "localhost:8010"
  tmp_path: "/home/hilbertspace"
  cookie_hash: "dEaxmDC3EDxNfcZ6+98mfDaesDdkwhbcsw+ELrEjfe4="
  cookie_encryption: "SdiVzqKa/nxLYcwlU2GcY3gNHE2ifiIHDHGDpBUsa68="

