---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Check if peroot repo is already configured.
  stat: "path=/etc/yum.repos.d/proot.repo"
  register: proot_repofile_result

- name: Install EPEL repo.
  package:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists

- name: Install proot repo.
  yum_repository:
    name: proot
    description: copr proot repo
    baseurl: "https://copr-be.cloud.fedoraproject.org/results/jlaska/proot/epel-7-$basearch/"
  when: not epel_repofile_result.stat.exists

- name: Import proot GPG key
  rpm_key:
    key: "https://copr-be.cloud.fedoraproject.org/results/jlaska/proot/pubkey.gpg"
    state: present
  when: not epel_repofile_result.stat.exists

- name: Install dependencies packages
  package: name={{ item }} state=present
  with_items: "{{ tensor_packages_dependencies }}"
  notify:
    - "Start Docker"
    - "Enable Docker"