# Setup docker repository

- name: "Add docker key"
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: "Add Ansible key"
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367

- name: Install apt dependencies
  package: name={{ item }} state=present
  with_items: "{{ packaging_dependencies }}"

- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
    state: present

- apt_repository:
    repo: 'ppa:ansible/ansible'
  when: ansible_distribution == 'Ubuntu'

- apt_repository:
    repo: 'ppa:ansible/proot'
  when: ansible_distribution == 'Ubuntu'

- name: Install dependencies packages
  package: name={{ item }} state=present force=yes
  with_items: "{{ tensor_packages_dependencies }}"
  notify:
    - "Start Docker"
    - "Enable Docker"
