version: '2'
services:
  mongo:
    build:
      context: ./mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_ROOT_USER: root
      MONGO_APP_USER: tensor
      MONGO_APP_PASSWORD: tensor
      MONGO_APP_DATABASE: tensordb
    tty: true
    stdin_open: true
    networks:
      tensornet:
        aliases:
          - mongo
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
    tty: true
    stdin_open: true
    networks:
      tensornet:
        aliases:
          - redis

  tensor:
    image: gamunu/tensor:latest
    volumes:
      - ../../data/tensor:/data
    ports:
      - '8010:8010'
    restart: always
    environment:
      TENSOR_PORT: ":8010"
      PROJECTS_HOME: "/data"
      TENSOR_DB_USER: tensor
      TENSOR_DB_PASSWORD: tensor
      TENSOR_DB_NAME: tensordb
      TENSOR_DB_REPLICA: ""
      TENSOR_DB_HOSTS: "mongo:27017"
      TENSOR_REDIS_HOST: "redis:6379"
      TENSOR_SALT: "8m86pie1ef8bghbq41ru!de4"
    tty: true
    stdin_open: true
    networks:
      tensornet:
        aliases:
          - tensor

networks:
  tensornet:
    driver: bridge