version: '2'
services:
  mongo:
    build:
      context: ./mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_ROOT_USER: root
      MONGO_APP_USER: tensor
      MONGO_APP_PASSWORD: tensor
      MONGO_APP_DATABASE: tensordb
    tty: true
    stdin_open: true
    networks:
      tensornet:
        aliases:
          - mongo

  tensor:
    build:
      context: ./tensor
    volumes:
      - ../../:/go/src/bitbucket.pearson.com/apseng/tensor
    ports:
      - '8010:8010'
    restart: always
    tty: true
    stdin_open: true
    networks:
      tensornet:
        aliases:
          - tensor

networks:
  tensornet:
    driver: bridge