version: '2'
services:
  mongo1:
    build: .
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_ROLE: primary
      MONGO_SECONDARY: mongo2
      MONGO_ARBITER: mongo3
      MONGO_ROOT_USER: root
      MONGO_APP_USER: hilbert
      MONGO_APP_PASSWORD: hilbert
      MONGO_APP_DATABASE: hilbertspace
    tty: true
    stdin_open: true
    networks:
      hilbertnet:
        aliases:
          - mongo1

  mongo2:
    build: .
    ports:
      - '27018:27017'
    restart: always
    tty: true
    stdin_open: true
    networks:
      hilbertnet:
        aliases:
          - mongo2

  mongo3:
    build: .
    ports:
       - '27019:27017'
    restart: always
    environment:
      JOURNALING: 'no'
    tty: true
    stdin_open: true
    networks:
      hilbertnet:
        aliases:
          - mongo3

networks:
  hilbertnet:
    driver: bridge