---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  package:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists

- name: Allow port 6379 through firewalld
  firewalld:
    port: 6379/tcp
    permanent: true
    immediate: true
    state: enabled
  ignore_errors: yes # If firealld is not enabled

- name: Ensure Redis is installed.
  package:
    name: "{{ redis_package }}"
    state: present