#Golang

go_tarball: "go1.7.4.linux-amd64.tar.gz"
go_tarball_checksum: "sha256:47fda42e46b4c3ec93fa5d4d4cc6a748aa3f9411a2a2b7e08e3a6d80d753ec8b"
go_version_target: "go version go1.7.1 linux/amd64"

mongodb_host: "127.0.0.1:27017"
mongodb_user: "tensor"
mongodb_password: "tensor"
mongodb_database: "tensordb"
mongodb_replica_set: ""
redis_host: "127.0.0.1:6379"
tensor_port: ":8010"
tensor_projects_home: "/data/tensor"
tensor_salt: "8m86pie1ef8bghbq41ru!de4"


tensor_conf_path: /etc/tensor.conf

docker_compose_version: 1.10.0

epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"


go_download_location: "https://storage.googleapis.com/golang/{{ go_tarball }}"

inventory_plugins:
  - azure_rm.py
  - cloudforms.py
  - ec2.py
  - foreman.py
  - gce.py
  - openstack.py
  - rax.py
  - tensorrest.py
  - vmware.py
  - windows_azure.py